const portfoliophotos = [
  {
    src: require('../../assets/RE_assets/AdobeStock_162479912.jpeg'),
    title: 'First Space Elevator',
    category: 'Awards',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/AdobeStock_66781279.jpeg'),
    title: 'Singapore Tower',
    category: 'Commercial Projects',
    to: '/commercial',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/vancouver.jpg'),
    title: 'New Vancouver Development',
    category: 'Residential Projects',
    to: '/residential',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/bestdesign.jpeg'),
    title: 'Best Elevator Design Award',
    category: 'Awards',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/innovation.jpg'),
    title: 'Best Elevator Innovation Award',
    category: 'Awards',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/managed.jpg'),
    title: 'Best Managed Elevator Company Award',
    category: 'Awards',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/h1.jpg'),
    title: 'Most Favored Elevator Award',
    category: 'Awards',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/dubai.jpg'),
    title: 'Dubai Development',
    category: 'Commercial Projects',
    to: '/commercial',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/ny.jpg'),
    title: 'New York City Development',
    category: 'Residential Projects',
    to: '/residential',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/mt.jpg'),
    title: 'Montreal Hotel Development',
    category: 'Commercial Projects',
    to: '/commercial',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/AdobeStock_3294993.jpeg'),
    title: 'Hong Kong Development',
    category: 'Residential Projects',
    to: '/residential',
    width: 100,
    height: 100,
  },
  {
    src: require('../../assets/RE_assets/AdobeStock_72034307.jpeg'),
    title: 'Best Glass Elevator Award',
    category: 'Awards',
    width: 100,
    height: 100,
  },
];

export default portfoliophotos;
